# Generated by Django 5.2.4 on 2025-12-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_place', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('indication', models.CharField(max_length=255, null=True)),
                ('pseudo', models.CharField(max_length=25)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.categorie')),
            ],
        ),
    ]
