# Generated by Django 5.2.4 on 2025-12-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='Places.categorie'),
        ),
        migrations.AlterField(
            model_name='place',
            name='indication',
            field=models.CharField(default='', max_length=255),
        ),
    ]
